### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ric79** [QualiSystems/Sandbox-Jenkins-Plugin#29]
Hello,
I installed the  plugin and created this simple pipeline

```
timeout(time: 20, unit: 'MINUTES') {
  node('xxx.tp.cselt.it') {
    try {
        def workspace = pwd()
        
        stage 'Reservation'
        withSandbox(maxDuration: 60, name: 'RM_Check') {
            echo "${env.SANDBOX_ID}"
            // some blocks
        }
    }
    catch (err) {
        currentBuild.result = 'FAILURE'
        emailext attachLog: true,
                          body: 'Maggiori info: <a href="' + env.BUILD_URL + '">Job "' + env.JOB_NAME + '" (' + env.BUILD_NUMBER + ') </>',
                   compressLog: true,
                       subject: env.JOB_NAME + ': build fallito',
                            to: email_receiver_list
        throw err
    }    
  }
} 
```          

The plugin is configured with ignore certificate. I get this error on output: 
```
Started by user Russo Riccardo
[Pipeline] timeout
[Pipeline] {
[Pipeline] node
Running on xxx.tp.cselt.it in /home/xxx/workspace/xxx/Rilascio_xxx_Cloudshell
[Pipeline] {
[Pipeline] pwd
[Pipeline] stage (Reservation)
Entering stage Reservation
Proceeding
[Pipeline] withSandbox
CloudShell Starting!
startBlueprint: sandbox name set to be xxx/Rilascio_xxx_Cloudshell_804f9
[Pipeline] // withSandbox
[Pipeline] emailext
Job type does not allow token replacement.
Job type does not allow token replacement.
Request made to compress build log
Job type does not allow token replacement.
Job type does not allow token replacement.
Sending email to: riccardo.russo@telecomitalia.it
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // timeout
[Pipeline] End of Pipeline
java.lang.NullPointerException
	at com.quali.cloudshell.SandboxAPIProxy.StartBluePrint(SandboxAPIProxy.java:50)
	at com.quali.cloudshell.SandboxApiGateway.startBlueprint(SandboxApiGateway.java:57)
	at org.jenkinsci.plugins.cloudshell.steps.StepsCommon.StartSandbox(StepsCommon.java:36)
	at org.jenkinsci.plugins.cloudshell.steps.SandboxStep$Execution.CreateSandbox(SandboxStep.java:107)
	at org.jenkinsci.plugins.cloudshell.steps.SandboxStep$Execution.start(SandboxStep.java:82)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:138)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:113)
	at groovy.lang.GroovyObject$invokeMethod$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:151)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:21)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:115)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:149)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:146)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:123)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:123)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:15)
	at WorkflowScript.run(WorkflowScript:7)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:55)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:106)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:79)
	at sun.reflect.GeneratedMethodAccessor554.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ClosureBlock.eval(ClosureBlock.java:40)
	at com.cloudbees.groovy.cps.Next.step(Next.java:58)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:32)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:29)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:29)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:164)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:297)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$000(CpsThreadGroup.java:78)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:206)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:204)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Finished: FAILURE
```

The environment exists:
[![2016-09-14_081440.png](https://s22.postimg.org/b7wkr8lwh/2016_09_14_081440.png)](https://postimg.org/image/6yrup2in1/)

(We use a proxy in our company)

**Comment by doppleware** [comment]
Hi Ricardo,
Is any sandbox reservation being created in CloudShell?
Also make sure the blueprint environment is public - the sandbox API will only work with public blueprints.
Can you include the complete pipeline script you're using?

**Comment by ric79** [comment]
Hello,
the pipeline at the moment is just this one :). I started now using the plugin. 
I tried to put the env public, but still I get the same error. No reservation on that env at the moment shown on CloudShell
I'm using Jenkins 2.13

**Comment by doppleware** [comment]
Which CloudShell release are you using? Can you also share your Jenkins configuration page?

**Comment by ric79** [comment]
Do you want that I send to you an online meeting for 9:30 italian time?

**Comment by doppleware** [comment]
Hi Ricardo,
I'm traveling so can't meet until tomorrow, I'll check if someone else is available to assist.
Thanks,
Roni

**Comment by ric79** [comment]
Thanks, I think that it is better for your team to see live the system

**Comment by ric79** [comment]
Ok.
Now it is working. I was missing the CloudShell Sandbox API

**Comment by doppleware** [comment]
Great, will opened issue #30 to improve error handling in this scenario
